-- MySQL Script generated by MySQL Workbench
-- 08/25/17 17:28:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Iuteb_asignaturas
-- -----------------------------------------------------
-- Base de datos para aplicacion de asignatura del IUTEB

-- -----------------------------------------------------
-- Schema Iuteb_asignaturas
--
-- Base de datos para aplicacion de asignatura del IUTEB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Iuteb_asignaturas` ;
USE `Iuteb_asignaturas` ;

-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`alumnos` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `contrasena` INT(20) NULL,
  `nombre_completo` VARCHAR(45) NULL,
  `cedula` INT(30) NULL,
  `correo` VARCHAR(45) NULL,
  `fecha_ingreso` DATE NULL,
  `telefono` VARCHAR(45) NULL,
  `foto_perfil` VARCHAR(45) NULL,
  `pnf` VARCHAR(45) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_alumno`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`profesores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  `nombre_completo` VARCHAR(45) NULL,
  `cedula` INT(20) NULL,
  `correo` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `pnf` VARCHAR(45) NULL,
  `foto_perfil` VARCHAR(45) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  UNIQUE INDEX `contrasena_UNIQUE` (`contrasena` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`malla_curricular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`malla_curricular` (
  `id_malla` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_malla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`asistencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`asistencias` (
  `id_asistencia` INT NOT NULL AUTO_INCREMENT,
  `id_seccion` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `id_profesor` INT(10) NULL,
  PRIMARY KEY (`id_asistencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`administradores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`basededatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`basededatos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`publicaciones` (
  `id_publicacion` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `id_seccion` INT NULL,
  `id_profesor` INT NULL,
  `fecha_publicacion` VARCHAR(45) NULL,
  `nombre_archivo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_publicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`materias` (
  `id_materia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `trimestre` INT NULL,
  `id_malla` VARCHAR(45) NULL,
  PRIMARY KEY (`id_materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`app_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`app_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `version` VARCHAR(45) NULL,
  `fecha_creaccion` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`secciones` (
  `id_seccion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `id_materia` VARCHAR(45) NULL,
  PRIMARY KEY (`id_seccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`alumnos_has_asistencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`alumnos_has_asistencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_seccion` INT(12) NULL,
  `id_alumno` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  `asistio` INT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`alumnos_has_secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`alumnos_has_secciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_alumno` INT(20) NULL,
  `id_seccion` INT(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
