-- MySQL Script generated by MySQL Workbench
-- 09/21/17 19:40:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Iuteb_asignaturas
-- -----------------------------------------------------
-- Base de datos para aplicacion de asistencias del IUTEB
-- 
-- Luis Torres
-- Michel Novellino
-- Adrian Flores

CREATE SCHEMA IF NOT EXISTS `Iuteb_asignaturas` ;
USE `Iuteb_asignaturas` ;

-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`malla_curricular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`malla_curricular` (
  `id_malla` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_malla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `contrasena` INT NULL,
  `nombre_completo` VARCHAR(45) NULL,
  `cedula` INT NULL,
  `correo` VARCHAR(45) NULL,
  `fecha_ingreso` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `telefono` INT NULL,
  `foto_perfil` VARCHAR(450) NULL,
  `id_malla` INT NULL,
  `estado` ENUM('0', '1') NULL DEFAULT '1',
  `tipo` ENUM('Estudiante', 'Administrador', 'Profesor') NULL DEFAULT 'Estudiante',
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  INDEX `user_id_malla_idx` (`id_malla` ASC),
  CONSTRAINT `user_id_malla`
    FOREIGN KEY (`id_malla`)
    REFERENCES `Iuteb_asignaturas`.`malla_curricular` (`id_malla`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`basededatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`basededatos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(100) NULL,
  `date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `filename_UNIQUE` (`filename` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`asignaturas` (
  `id_asignatura` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `trimestre` INT NULL,
  `id_malla` INT NULL,
  PRIMARY KEY (`id_asignatura`),
  INDEX `m_id_malla_idx` (`id_malla` ASC),
  CONSTRAINT `m_id_malla`
    FOREIGN KEY (`id_malla`)
    REFERENCES `Iuteb_asignaturas`.`malla_curricular` (`id_malla`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`secciones` (
  `id_seccion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `id_asignatura` INT NULL,
  `codigo` VARCHAR(45) NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_seccion`),
  INDEX `s_id_materia_idx` (`id_asignatura` ASC),
  INDEX `s_id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `s_id_asignatura`
    FOREIGN KEY (`id_asignatura`)
    REFERENCES `Iuteb_asignaturas`.`asignaturas` (`id_asignatura`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `s_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Iuteb_asignaturas`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`publicaciones` (
  `id_publicacion` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `id_seccion` INT NULL,
  `id_usuario` INT NULL,
  `fecha_publicacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `nombre_archivo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_publicacion`),
  INDEX `p_id_usuario_idx` (`id_usuario` ASC),
  INDEX `p_id_seccion_idx` (`id_seccion` ASC),
  CONSTRAINT `p_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Iuteb_asignaturas`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `p_id_seccion`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `Iuteb_asignaturas`.`secciones` (`id_seccion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`app_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`app_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `version` VARCHAR(45) NULL,
  `fecha_creaccion` DATETIME NULL,
  `descripcion` VARCHAR(900) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`alumnos_has_asistencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`alumnos_has_asistencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_seccion` INT NULL,
  `id_usuario` INT NULL,
  `fecha` DATETIME NULL,
  `asistio` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `a_has_id_usuarios_idx` (`id_usuario` ASC),
  INDEX `a_has_id_seccion_idx` (`id_seccion` ASC),
  CONSTRAINT `a_has_id_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Iuteb_asignaturas`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `a_has_id_seccion`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `Iuteb_asignaturas`.`secciones` (`id_seccion`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`alumnos_has_secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`alumnos_has_secciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(20) NULL,
  `id_seccion` INT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `al_has_id_usuario_idx` (`id_usuario` ASC),
  INDEX `al_has_s_id_seccion_idx` (`id_seccion` ASC),
  CONSTRAINT `al_has_s_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Iuteb_asignaturas`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `al_has_s_id_seccion`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `Iuteb_asignaturas`.`secciones` (`id_seccion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
