-- MySQL Script generated by MySQL Workbench
-- 08/28/17 17:04:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Iuteb_asignaturas
-- -----------------------------------------------------
-- Base de datos para aplicacion de asistencias del IUTEB
-- 
-- Luis Torres
-- Michel Novellino
-- Adrian Flores

-- -----------------------------------------------------
-- Schema Iuteb_asignaturas
--
-- Base de datos para aplicacion de asistencias del IUTEB
-- 
-- Luis Torres
-- Michel Novellino
-- Adrian Flores
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Iuteb_asignaturas` ;
USE `Iuteb_asignaturas` ;

-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`malla_curricular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`malla_curricular` (
  `id_malla` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_malla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `contrasena` INT(20) NULL,
  `nombre_completo` VARCHAR(45) NULL,
  `cedula` INT(30) NULL,
  `correo` VARCHAR(45) NULL,
  `fecha_ingreso` DATETIME NULL,
  `telefono` INT(25) NULL,
  `foto_perfil` VARCHAR(450) NULL,
  `id_malla` INT NULL,
  `estado` INT NULL,
  `tipo` VARCHAR(40) NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  INDEX `malla_idMalla_idx` (`id_malla` ASC),
  CONSTRAINT `malla_idMalla`
    FOREIGN KEY (`id_malla`)
    REFERENCES `Iuteb_asignaturas`.`malla_curricular` (`id_malla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`materias` (
  `id_materia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `trimestre` INT NULL,
  `id_malla` INT NULL,
  PRIMARY KEY (`id_materia`),
  INDEX `m_malla_idMalla_idx` (`id_malla` ASC),
  CONSTRAINT `m_malla_idMalla`
    FOREIGN KEY (`id_malla`)
    REFERENCES `Iuteb_asignaturas`.`malla_curricular` (`id_malla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`secciones` (
  `id_seccion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `id_materia` INT NULL,
  `codigo` VARCHAR(45) NULL,
  `id_usuario` INT(10) NULL,
  PRIMARY KEY (`id_seccion`),
  INDEX `materia_idMateria_idx` (`id_materia` ASC),
  INDEX `Sec_usuario_idUsuario_idx` (`id_usuario` ASC),
  CONSTRAINT `materia_idMateria`
    FOREIGN KEY (`id_materia`)
    REFERENCES `Iuteb_asignaturas`.`materias` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Sec_usuario_idUsuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Iuteb_asignaturas`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`asistencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`asistencias` (
  `id_asistencia` INT NOT NULL AUTO_INCREMENT,
  `id_seccion` INT NULL,
  `fecha` DATE NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_asistencia`),
  INDEX `a_secciones_idSeccion_idx` (`id_seccion` ASC),
  INDEX `a_usuarios_idUsuario_idx` (`id_usuario` ASC),
  CONSTRAINT `a_secciones_idSeccion`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `Iuteb_asignaturas`.`secciones` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `a_usuarios_idUsuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Iuteb_asignaturas`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`basededatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`basededatos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`publicaciones` (
  `id_publicacion` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `id_seccion` INT NULL,
  `id_usuario` INT NULL,
  `fecha_publicacion` DATETIME NULL,
  `nombre_archivo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_publicacion`),
  INDEX `p_secciones_idSeccion_idx` (`id_seccion` ASC),
  INDEX `p_usuario_idUsuario_idx` (`id_usuario` ASC),
  CONSTRAINT `p_secciones_idSeccion`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `Iuteb_asignaturas`.`secciones` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `p_usuario_idUsuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Iuteb_asignaturas`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`app_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`app_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `version` VARCHAR(45) NULL,
  `fecha_creaccion` DATETIME NULL,
  `descripcion` VARCHAR(900) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`alumnos_has_asistencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`alumnos_has_asistencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_seccion` INT NULL,
  `id_usuario` INT NULL,
  `fecha` DATETIME NULL,
  `asistio` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `aha_usuarios_idUsuario_idx` (`id_usuario` ASC),
  INDEX `aha_secciones_idSeccion_idx` (`id_seccion` ASC),
  CONSTRAINT `aha_usuarios_idUsuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Iuteb_asignaturas`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `aha_secciones_idSeccion`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `Iuteb_asignaturas`.`secciones` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Iuteb_asignaturas`.`alumnos_has_secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Iuteb_asignaturas`.`alumnos_has_secciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(20) NULL,
  `id_seccion` INT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `ahs_usuario_idUsuario_idx` (`id_usuario` ASC),
  INDEX `ahs_secciones_idSeccion_idx` (`id_seccion` ASC),
  CONSTRAINT `ahs_usuario_idUsuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Iuteb_asignaturas`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ahs_secciones_idSeccion`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `Iuteb_asignaturas`.`secciones` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
